export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return <div className="flex flex-row h-screen w-full ">{children}</div>;
}
